config/routes.rb
Rails.application.routes.draw do

  get 'software/new'

  get 'users/new'

  get 'users/new'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' =>'static_pages#about'

  get 'software' => 'static_pages#software'

  get 'contact' => 'messages#contact'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :messages, only: [:contact, :create]

  resources :compositions

  resources :users

end

app/models/composition.rb
class Composition < ActiveRecord::Base
end

app/models/message.rb
class Message
	include ActiveModel::Model
	attr_accessor :name, :email, :subject, :content
	validates :name, :email, :subject, :content, presence: true
end

app/models/software.rb
class Software < ActiveRecord::Base
	validates :name,  presence: true
	VALID_SCRIPT_REGEX = /[.]{1}/
	validates :script, presence: true, format: { with: VALID_SCRIPT_REGEX }, uniqueness: true

end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

    private 

  #confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
	before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

	def new
		@composition = Composition.new
	end

	def create
		@composition = Composition.new(composition_params)
		if @composition.save
			flash[:success] = "Composition created"
			redirect_to @composition
		else
			render 'new'
		end
	end
	
	def index
		@compositions = Composition.all.order("compositions.year DESC, compositions.title")
	end

	def show
		@composition = Composition.find(params[:id])
	end

	def edit
		@composition = Composition.find(params[:id])
	end

	def update
		@composition = Composition.find(params[:id])
		if @composition.update_attributes(composition_params)
			flash[:success] = "Composition Updated"
			redirect_to compositions_path
		else
			render 'edit'
		end
	end
		

	def destroy
		Composition.find(params[:id]).destroy
		flash[:success] = "Composition deleted"
		redirect_to compositions_path
	end

	private 

	def composition_params
		params.require(:composition).permit(:title, :forces, :year, :programme_note, :streaming, :image)
	end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def contact
  	@message = Message.new
  end

  def create
  	@message = Message.new(message_params)
    captcha_message = "Big Error!"
  	if verify_recaptcha(recaptcha_response: "There was a mistake in your captcha" ) && @message.valid?
      MessageMailer.message_me(@message).deliver_now
      redirect_to contact_path
      flash[:success] = "Message sent"
    elsif !verify_recaptcha
      flash[:error] = "Something went wrong with the captcha. Are you human?"
    else
      flash[:error] = "You must be missing information"
  	end
  end

  private

  def message_params
  	params.require(:message).permit(:name, :email, :subject, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_back_or about_path
  	else
  		flash.now[:error] = 'Invalid email/password combination' 
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to about_path
  end
  
end

app/controllers/software_controller.rb
class SoftwareController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def composition
  end

  def contact
  end

  def software
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Jason Post - Composer, Sound Artist, Developer"
		if page_title.empty? #boolean check
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	#logs in the given user
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end


	# Stores the URL trying to be accessed.
	def store_location
		session[:forwarding_url] = request.url if request.get?
	end

end

app/helpers/software_helper.rb
module SoftwareHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/compositions/edit.html.erb
<% provide(:title, "Edit Composition") %>
<h1>Update Composition</h1>

<div class="row">
	<div class="col-md-6 col-md-offset3">
		<%= form_for @composition, :method => :PATCH do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>

		<%= f.label :forces %>
		<%= f.text_field :forces, class: 'form-control' %>

		<%= f.label :year %>
		<%= f.text_field :year, class: 'form-control' %>

		<%= f.label :programme_note %>
		<%= f.text_field :programme_note, class: 'form-control' %>

		<%= f.label :streaming %>
		<%= f.text_field :streaming, class: 'form-control' %>

		<%= f.label :image %>
		<%= f.text_field :image, class: 'form-control' %>
		<br>
		<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>

app/views/compositions/index.html.erb
<% provide(:title, "Compositions") %>
<h1>Compositions</h1>
<% @compositions.each do |composition| %>
<%= link_to(composition) do %>
<div id="paragraph">
	<div class="row">
		<div class="col-md-9">
			<p class="title"><h3> <%= composition.title %></h3></p>
			<p class="year"><%= composition.year %></p>
			<p class="forces"><%= composition.forces %></p>
			<% if logged_in? %>
			<%= link_to "delete", composition, method: :delete, data: { confirm: "Are you sure?" } %>
			<% end %>
		</div>
	</div>
</div>
<%end%>
<br>
<% end %>

app/views/compositions/new.html.erb
<% provide(:title, "New Composition") %>
<% provide(:button_text, 'Create Composition') %>
<h1>Create Composition</h1>

<div class="row">
	<div class="col-md-6 col-md-offset3">
		<%= form_for(@composition) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>

		<%= f.label :forces %>
		<%= f.text_field :forces, class: 'form-control' %>

		<%= f.label :year %>
		<%= f.text_field :year, class: 'form-control' %>

		<%= f.label :programme_note %>
		<%= f.text_field :programme_note, class: 'form-control' %>

		<%= f.label :streaming %>
		<%= f.text_field :streaming, class: 'form-control' %>

		<%= f.label :image %>
		<%= f.text_field :image, class: 'form-control' %>
		<br>
		<%= f.submit "Create Composition", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/compositions/show.html.erb
<% provide(:title, @composition.title) %>
<h1><%= @composition.title %></h1>
<div id="paragraph">
  <p>Composed <%= @composition.year %></p>
  <p class="forces"><%= @composition.forces %></p>
  <br>
  <%=raw @composition.streaming %>
  <br><br>
  <p class="programme-note"><%= @composition.programme_note %></p>
  <br><br><br>
  <p class="score note">All available scores can be purchased from SOUNZ - Centre for New Zealand Music <a href="http://sounz.org.nz/contributor/composer/1837">here.</a></p>

  <% if logged_in? %>
  <%= link_to "Edit", edit_composition_path(@composition) %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
  	<ul>


  	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="headerColour">
  <div class="container">
  	<%= link_to "Jason Post", root_path, id: "logo" %> 
  	<nav>
  		<ul class="nav navbar-nav navbar-right" id="heading"> 
  			<li><%= link_to "About", about_path, id: "headTextCol" %></li>
  			<li><%= link_to "Compositions", compositions_path, id: "headTextCol" %></li>
  			<li><%= link_to "Software", software_path, id: "headTextCol" %></li>
  			<li><%= link_to "Contact", contact_path, id: "headTextCol" %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Admin <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" id="dropdown-format">
              <li><%= link_to "Change bio", current_user %></li>
              <li><%= link_to "Create Composition", new_composition_path %></li>
              <li><%= link_to "Settings", about_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul> 
          </li>
          <%else%>
          <li></li>
        <%end%>   
  		</ul> 
  	</nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link rel="shortcut icon" href="https://s3-us-west-2.amazonaws.com/composerapp/icon.ico" type="image/png">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class ="container">
		<% flash.each do |message_type, message| %>
		<div class="alert-alert-<%= message_type %>"><%= message %></div>
		<%end%>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/messages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
      </h2>

      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      <ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <br>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <br>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
<br><%= recaptcha_tags %><br>
  <div class="actions">
    <%= f.submit 'Send', class: 'button' %>
  </div>
<% end %>

app/views/messages/create.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
      </h2>

      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      <ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <br>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <br>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
<br><%= recaptcha_tags %><br>
  <div class="actions">
    <%= f.submit 'Send', class: 'button' %>
  </div>
<% end %>

app/views/messages/new.html.erb
<h1>Contact</h1>
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
      </h2>

      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      <ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <br>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <br>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
<br><%= recaptcha_tags %><br>
  <div class="actions">
    <%= f.submit 'Send', class: 'button' %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %> 
<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li> 
		<% end %>
		</ul>
	</div> 
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<%= f.text_area :content, placeholder: "Compose new micropost..." %>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<span class="picture">
	<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
</span>
<% end %>

<script type="text/javascript">
$('#micropost_picture').bind('change', function() {
	var size_in_megabytes = this.files[0].size/1024/1024;
	if (size_in_megabytes > 5) {
		alert('Maximum file size is 5MB. Please choose a smaller file.');
	}
});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>"> 
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat"> 
			<%= @user.followers.count %>
		</strong>
		followers
	</a> 
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/software/new.html.erb
<h1>Software#new</h1>
<p>Find me in app/views/software/new.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h2>
	<div id="paragraph">
		<br>
		<img
		style="display:block; margin: auto; width:50%;"
	 	src="https://s3-us-west-2.amazonaws.com/composerapp/DSC_0015.jpg"/>
		<br>
		<p style="text-align:center;">Short biography for concert programs</p>

		<br>

		<p class="shorter-text">Jason Post is a composer and sound artist from New Zealand. His main interests and composition techniques stem from spectral music, soundscape studies and live electronics. He has just completed an MMus degree in Composition at the New Zealand School of Music in Wellington, supervised by Michael Norris and Dugal McKinnon.</p>

		<p class="shorter-text">Jason's sound installations have been shown at the Adam Art Gallery at Victoria University of Wellington and at the Window Gallery at the University of Auckland. His music has been workshopped and played by the New Zealand String Quartet, the NZSM Orchestra, Karlheinz Company, and the SMP Ensemble. In 2013, he completed his first short film score for Unnatural History by Alex Backhouse, which had its international premiere at the 2014 Locarno Film Festival.</p>

	<p class="shorter-text">Upcoming projects include the soundtrack and sound design for a new short film by Alex Backhouse, and a new work for flute and live electronics.</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %> 
<h1>Help</h1>
<p id="paragraph">If you find something that doesn't work on this website, please contact me <a href="#">here</a>.</p>

app/views/static_pages/software.html.erb
<% provide(:title, "Software") %>
<h1>Software</h1>
<p id="paragraph">A few javascript applications and other things await... in the mean time, please see my <a href="https://github.com/jasonwpost">GitHub</a>.</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>